# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Increases the command timeout to prevent warnings
command_timeout = 1000

# Removes the blank line between shell prompts
add_newline = false

# Custom format configuration
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$kubernetes\
$terraform\
$docker_context\
$nodejs\
$package\
$memory_usage\
$battery\
$time\
$shell\
$cmd_duration\
$line_break\
$character"""

# Fill module
[fill]
symbol = "─"
style = "bold black"

# Replace the "❯" symbol in the prompt with "󰆍]"
[character]
success_symbol = "[󰆍](#FF0000)"
error_symbol = "[󰆍](#FF0000)"

# Cloud/Infrastructure tools
[terraform]
symbol = "󱁢 "
format = "[$symbol$version]($style) "
style = "bold 105"

[kubernetes]
symbol = "󱃾 "
format = '[$symbol$context( \($namespace\))]($style) '
style = "bold blue"
disabled = false

[docker_context]
symbol = "󰡨 "
format = "via [$symbol$context]($style) "
style = "blue bold"

# Development tools
[nodejs]
symbol = "󰎙 "
format = "via [$symbol$version](bold green) "

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "
style = "208"

# Git information
[git_branch]
symbol = "󰘬 "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

# System info
[username]
style_user = "bold blue"
format = "[$user]($style) "
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](bold red) "
disabled = false

[directory]
style = "bold cyan"
read_only = "󰌾 "
truncation_length = 4
truncate_to_repo = false

# Command duration
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow) "

# Time
[time]
disabled = false
format = '[\[ $time \]](#A575F4) '
time_format = "%R"
style = "bold #A575F4"

# Shell indicator
[shell]
fish_indicator = "🐟 "
powershell_indicator = "⚡ "
unknown_indicator = "❓ "
style = "cyan bold"
disabled = false

# Battery module
[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "
unknown_symbol = "⌛ "
empty_symbol = "! "

[[battery.display]]
threshold = 100
style = "bold green"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 20
style = "bold red"

# Memory usage
[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛 "
style = "bold dimmed green"
format = "$symbol[${ram}]($style) "

# Add after your other git configurations
[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

